services:
  - type: web
    name: xevytalk
    env: node
    buildCommand: npm install --prefix client && npm run build --prefix client
    startCommand: node server/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: xevytalk-db
          property: connectionString
    plan: free

databases:
  - name: xevytalk-db
    databaseName: xevytalk
    user: xevytalk_user
    plan: free
